### ISSUE TITLE
Update mdast to remark

### ISSUE THREAD

**Issue by wooorm** [ben-eb/mdast-highlight.js#3]
Hey! Just wanted ping and request a name change from mdast to remark.

You’ve probably already seen it but here’s a list of [tips for updating](https://github.com/wooorm/remark/blob/master/doc/plugins.md#renaming-from-mdast-to-remark). And here’s a list of reasons [why to update](https://github.com/wooorm/remark/releases/tag/3.0.0).

Let me know if I can help! :smile:

**Comment by ben-eb** [comment]
I've been meaning to get around to this (& others) but updating is quite time consuming, spent at least an hour converting https://github.com/ben-eb/mdast-autolink-headings. I'll get around to it but it's low down on the priority list right now.

**Comment by wooorm** [comment]
Really? Sorry, I can imagine. I’ll do a PR of the replaces!

**Comment by ben-eb** [comment]
Yep, wasn't as simple as 'just' a name change either because of babel 6 and babel-tape-runner 1.3.0, so had to update the whole module. In the process of upgrading modules I maintain to babel 6, ava, eslint etc but it's a slog. :frowning:

https://github.com/ben-eb/remark-autolink-headings/commit/31306a0b61ea3c9b204165df92e537ecde843126

**Comment by wooorm** [comment]
:anguished:

**Comment by ben-eb** [comment]
https://github.com/ben-eb/mdast-highlight.js/commit/0a13fe724df57856ba3178651fee44bd45343405

**Comment by wooorm** [comment]
Coool! :+1:
